
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_selects.yaml
input_text: !include input_text.yaml
sensor: !include_dir_merge_list sensors/
light: !include lights.yaml
switch: !include switches.yaml
recorder: !include recorder.yaml
utility_meter: !include utility_meters.yaml

logger:
  default: info

http:
  base_url: !secret domain
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

api:

alexa:
  smart_home:

input_number:
  dummy_power:
    name: Dummy power
    initial: 0
    min: 0
    max: 50
    step: 1
input_boolean:
  dummy_switch:
