
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_selects.yaml
sensor: !include_dir_merge_list sensors/
light: !include lights.yaml
recorder: !include recorder.yaml

logger:
  default: info

http:
  base_url: !secret domain
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

