#Shelly 2.5 luci cucina
# Solo relay 0, il relay 1 è configurato come light
- platform: mqtt
  name: "Pulsante led cucina"
  state_topic: "shellies/shelly25-luci_cucina/relay/0"
  command_topic: "shellies/shelly25-luci_cucina/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: false
